### PR TITLE
Slurm update

### PR DESCRIPTION
**Pull request by johnkit**
There are several reasons for this change:
* The original purpose was to fix incompatibilities with the current Slurm release, which has dropped two options --workdir and --unbuffered (as of March 2019).
* Also update the master branch requirements.txt to explicitly use girder 3
* And update most of the other requirements to more recent versions as well (but stick with celery 3).

### CODE REVIEW

**Comment by cjh1** [comment]
I am guess it failure is the result of bumping the ansible version.

**Comment by johnkit** [comment]
Oops, I never thought about python 2...

@cjh1 I might need your help on this. The same test is failing for me on cumulus:master. Maybe we can look at it next Monday or Tuesday?

**Comment by cjh1** [comment]
@johnkit Sure, sounds good.

**Comment by aronhelser** [comment]
Hey, I have another MR is progress that updates Ansible - https://github.com/Kitware/cumulus/pull/352 
I believe it is passing all Python 2 tests, except that I changed the job submission template to include 'env' and 'ls', and that I have a 'debug' ansible task in there.

My requirements.txt updates are very similar to yours - 
I think it makes sense for me to merge it after fixing the above issues - want to take a look?

**Comment by johnkit** [comment]
@aronhelser Yes, let's go with your requirements.txt changes (I was being a little too aggressive). So I will do one more force-push on this branch to be consistent with #352.

**Comment by johnkit** [comment]
I forgot one exception - I am going to keep girder-client 3.x

**Comment by aronhelser** [comment]
Yes, I needed to update girder-client - best to match with main girder version.

**Comment by johnkit** [comment]
On hold pending retest with NERSC once they are back online (tentatively Friday 13-Sep-2019).

**Comment by johnkit** [comment]
@cjh1 I'm not authorized to merge into master. Would you please push the button for me?

**Pull request merged**
