### PR TITLE
Cast from unicode to integer

### PR DESCRIPTION
**Pull request by johnkit**
When we changed the download_path() call to set upload=True, we hit an error in girder_client because the connection "size" value was a string (unicode) instead of an integer. I did not investigate why that connection size was a string, but instead cast it to an integer to fix the problem.

### CODE REVIEW

**Comment by cjh1** [comment]
@johnkit I push a commit that fixes the type issue in the NEWT specific part of the code, let me know if this works for you.

**Comment by johnkit** [comment]
@cjh1 Gosh I forgot about this PR. I am not an "approving reviewer" for this. Can you make me one, or can we get someone to review it please?

**Comment by johnkit** [comment]
Sorry, I forgot that I originated this guy. Actually, let me double-check tomorrow that I really did verify the fix back in April.

**Comment by cjh1** [comment]
@johnkit Should this one go in as well?

**Comment by johnkit** [comment]
YES. I *finally* retested and the fix is good to go. Thanks Chris.

**Pull request merged**
