### PR TITLE
Fix download_path(...) to correctly parent folders

### PR DESCRIPTION
**Pull request by cjh1**
Also added more extensive test case.

### CODE REVIEW

**Comment by cjh1** [comment]
Fixes #301

**Comment by cjh1** [comment]
@jourdain This should resolve the invalid folder parenting problem you were running into.

**Comment by jourdain** [comment]
cool thanks...

**Comment by cjh1** [comment]
Travis seems to have a problem with this test, am working on it ...

**Comment by jourdain** [comment]
Can I try that branch regardless of Travis issue? Or should I wait for you to fix it?

**Comment by cjh1** [comment]
yes

**Pull request merged**
