### PR TITLE
Add signal handler to log task exceptions

### PR DESCRIPTION
**Pull request by cjh1**

### CODE REVIEW

**Comment by cjh1** [comment]
@kotfic Could you take a quick look at this change?

**Comment by kotfic** [comment]
I'm a little confused why this is necessary -  shouldn't task_postrun_handler manage all task error handling? (re: the comment [here]( https://github.com/Kitware/cumulus/blob/task-exceptions/cumulus/taskflow/__init__.py#L485)) -  if task_postrun_handler doesn't sufficiently capture all instances of task failure we should probablly really clearly document in the code how task_exception_handler is different than task_failure_handler and why both are necessary.

**Comment by cjh1** [comment]
The problem is that the task_postrun_handler doesn't get any exception information, so that is why we need the task_failure handler as well. I will add some more documentation.

**Comment by cjh1** [comment]
I think I might remove the task_postrun_handler and replace it with a success and failure handler ...

**Comment by cjh1** [comment]
@kotfic PTAL now

**Comment by kotfic** [comment]
LGTM

**Pull request merged**
