### PR TITLE
Adds ec2 placement group variable to ec2 role

### PR DESCRIPTION
**Pull request by kotfic**
If ```placement_group``` is added to the cluster params this will set the placement group on launch.  See #213

### CODE REVIEW

**Comment by cjh1** [comment]
LGTM However, it does look like a placement group is something that needs to be created. So we will need to add support to our playbook to do this.

**Comment by kotfic** [comment]
It doesn't appear that ansible has a module that does this by default, https://github.com/ansible/ansible-modules-core/pull/1672 implements a module but it does not appear that it has been merged into core/extras

**Comment by kotfic** [comment]
@cjh1 can we go ahead and merge this?  we can address the placement group creation in a different PR?

**Comment by cjh1** [comment]
sure LGTM

**Pull request merged**
